@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.jooq.tables.references


import net.skullian.skyfactions.common.database.jooq.tables.FlywaySchemaHistory



/**
 * The table <code>flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY
