/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ElectionVotes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer election;
    private final byte[] uuid;
    private final String votedfor;

    public ElectionVotes(ElectionVotes value) {
        this.election = value.election;
        this.uuid = value.uuid;
        this.votedfor = value.votedfor;
    }

    public ElectionVotes(
        Integer election,
        byte[] uuid,
        String votedfor
    ) {
        this.election = election;
        this.uuid = uuid;
        this.votedfor = votedfor;
    }

    /**
     * Getter for <code>election_votes.election</code>.
     */
    public Integer getElection() {
        return this.election;
    }

    /**
     * Getter for <code>election_votes.uuid</code>.
     */
    public byte[] getUuid() {
        return this.uuid;
    }

    /**
     * Getter for <code>election_votes.votedFor</code>.
     */
    public String getVotedfor() {
        return this.votedfor;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ElectionVotes other = (ElectionVotes) obj;
        if (this.election == null) {
            if (other.election != null)
                return false;
        }
        else if (!this.election.equals(other.election))
            return false;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!Arrays.equals(this.uuid, other.uuid))
            return false;
        if (this.votedfor == null) {
            if (other.votedfor != null)
                return false;
        }
        else if (!this.votedfor.equals(other.votedfor))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.election == null) ? 0 : this.election.hashCode());
        result = prime * result + ((this.uuid == null) ? 0 : Arrays.hashCode(this.uuid));
        result = prime * result + ((this.votedfor == null) ? 0 : this.votedfor.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElectionVotes (");

        sb.append(election);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(votedfor);

        sb.append(")");
        return sb.toString();
    }
}
