/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionMembers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String factionname;
    private final byte[] uuid;
    private final String rank;

    public FactionMembers(FactionMembers value) {
        this.factionname = value.factionname;
        this.uuid = value.uuid;
        this.rank = value.rank;
    }

    public FactionMembers(
        String factionname,
        byte[] uuid,
        String rank
    ) {
        this.factionname = factionname;
        this.uuid = uuid;
        this.rank = rank;
    }

    /**
     * Getter for <code>faction_members.factionName</code>.
     */
    public String getFactionname() {
        return this.factionname;
    }

    /**
     * Getter for <code>faction_members.uuid</code>.
     */
    public byte[] getUuid() {
        return this.uuid;
    }

    /**
     * Getter for <code>faction_members.rank</code>.
     */
    public String getRank() {
        return this.rank;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FactionMembers other = (FactionMembers) obj;
        if (this.factionname == null) {
            if (other.factionname != null)
                return false;
        }
        else if (!this.factionname.equals(other.factionname))
            return false;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!Arrays.equals(this.uuid, other.uuid))
            return false;
        if (this.rank == null) {
            if (other.rank != null)
                return false;
        }
        else if (!this.rank.equals(other.rank))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.factionname == null) ? 0 : this.factionname.hashCode());
        result = prime * result + ((this.uuid == null) ? 0 : Arrays.hashCode(this.uuid));
        result = prime * result + ((this.rank == null) ? 0 : this.rank.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FactionMembers (");

        sb.append(factionname);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(rank);

        sb.append(")");
        return sb.toString();
    }
}
