version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      maven-plugin:
        patterns:
          - "org.apache.maven.plugins:*"
    ignore:
      # Log4j is provided by Minecraft, so the version should be kept in sync.
      - dependency-name: "org.apache.logging.log4j:log4j-core"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "major"
