/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database.tables.records;


import net.skullian.skyfactions.database.tables.TrustedPlayers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TrustedPlayersRecord extends UpdatableRecordImpl<TrustedPlayersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trusted_players.island_id</code>.
     */
    public TrustedPlayersRecord setIslandId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>trusted_players.island_id</code>.
     */
    public Integer getIslandId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trusted_players.uuid</code>.
     */
    public TrustedPlayersRecord setUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>trusted_players.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrustedPlayersRecord
     */
    public TrustedPlayersRecord() {
        super(TrustedPlayers.TRUSTED_PLAYERS);
    }

    /**
     * Create a detached, initialised TrustedPlayersRecord
     */
    public TrustedPlayersRecord(Integer islandId, String uuid) {
        super(TrustedPlayers.TRUSTED_PLAYERS);

        setIslandId(islandId);
        setUuid(uuid);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TrustedPlayersRecord
     */
    public TrustedPlayersRecord(net.skullian.skyfactions.database.tables.pojos.TrustedPlayers value) {
        super(TrustedPlayers.TRUSTED_PLAYERS);

        if (value != null) {
            setIslandId(value.getIslandId());
            setUuid(value.getUuid());
            resetChangedOnNotNull();
        }
    }
}
