name: SkyFactionsReborn
version: '${project.version}'
main: net.skullian.skyfactions.SkyFactionsReborn
api-version: 1.21
authors: [ Skullians, nouish ]
website: https://github.com/TerraByteDev/SkyFactionsReborn

depend: [ "FastAsyncWorldEdit", "WorldGuard", "WorldBorderAPI", "packetevents" ]
softdepend:
  - JukeBox
  - PlaceholderAPI
  - NoteBlockAPI
  - MythicMobs


libraries:
  - "com.zaxxer:HikariCP:5.1.0"
  - "org.xerial:sqlite-jdbc:3.46.0.0"
  - "net.dv8tion:JDA:5.0.1"
  - "com.fasterxml.jackson.core:jackson-databind:2.17.2"
  - "com.jeff-media:custom-block-data:2.2.2"
  - "org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10"
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.21"
  - "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.21"
  - "org.apache.commons:commons-collections4:4.4"
  - "net.sf.trove4j:core:3.1.0"
  - "com.fasterxml.jackson.core:jackson-core:2.17.0"
  - "com.fasterxml.jackson.core:jackson-annotations:2.17.2"
  - "org.slf4j:slf4j-api:2.0.9"
  - "org.jetbrains:annotations:23.0.0"
  - "com.google.code.findbugs:jsr305:3.0.2"
  - "com.google.crypto.tink:tink:1.14.1"
  - "com.google.protobuf:protobuf-java:3.25.3"
  - "com.google.errorprone:error_prone_annotations:2.18.0"
  - "com.google.code.gson:gson:2.10.1"
  - "net.objecthunter:exp4j:0.4.8"
  - "dev.dejvokep:boosted-yaml:1.3.5"
  - "org.incendo:cloud-paper:2.0.0-beta.10"