name: SkyFactionsReborn
version: '@version@'
main: net.skullian.skyfactions.SkyFactionsReborn
api-version: 1.21
authors: [ Skullians, nouish ]
website: https://github.com/TerraByteDev/SkyFactionsReborn

depend: [ "FastAsyncWorldEdit", "WorldGuard", "WorldBorderAPI", "packetevents" ]
softdepend:
  - JukeBox
  - PlaceholderAPI
  - NoteBlockAPI
  - MythicMobs
  - ZNPCsPlus
  - Citizens
  - fancynpcs