/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database;


import net.skullian.skyfactions.database.tables.*;
import net.skullian.skyfactions.database.tables.records.*;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FactionislandsRecord> FACTIONISLANDS__PK_FACTIONISLANDS = Internal.createUniqueKey(Factionislands.FACTIONISLANDS, DSL.name("pk_factionIslands"), new TableField[] { Factionislands.FACTIONISLANDS.ID }, true);
    public static final UniqueKey<FactionmembersRecord> FACTIONMEMBERS__PK_FACTIONMEMBERS = Internal.createUniqueKey(Factionmembers.FACTIONMEMBERS, DSL.name("pk_factionMembers"), new TableField[] { Factionmembers.FACTIONMEMBERS.UUID }, true);
    public static final UniqueKey<FactionsRecord> FACTIONS__PK_FACTIONS = Internal.createUniqueKey(Factions.FACTIONS, DSL.name("pk_factions"), new TableField[] { Factions.FACTIONS.NAME }, true);
    public static final UniqueKey<IslandsRecord> ISLANDS__PK_ISLANDS = Internal.createUniqueKey(Islands.ISLANDS, DSL.name("pk_islands"), new TableField[] { Islands.ISLANDS.ID }, true);
    public static final UniqueKey<PlayerdataRecord> PLAYERDATA__PK_PLAYERDATA = Internal.createUniqueKey(Playerdata.PLAYERDATA, DSL.name("pk_playerData"), new TableField[] { Playerdata.PLAYERDATA.UUID }, true);
    public static final UniqueKey<TrustedplayersRecord> TRUSTEDPLAYERS__PK_TRUSTEDPLAYERS = Internal.createUniqueKey(Trustedplayers.TRUSTEDPLAYERS, DSL.name("pk_trustedPlayers"), new TableField[] { Trustedplayers.TRUSTEDPLAYERS.ISLAND_ID }, true);
}
