/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database;


import net.skullian.skyfactions.database.tables.*;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>auditLogs</code>.
     */
    public static final Auditlogs AUDITLOGS = Auditlogs.AUDITLOGS;

    /**
     * The table <code>defenceLocations</code>.
     */
    public static final Defencelocations DEFENCELOCATIONS = Defencelocations.DEFENCELOCATIONS;

    /**
     * The table <code>factionBans</code>.
     */
    public static final Factionbans FACTIONBANS = Factionbans.FACTIONBANS;

    /**
     * The table <code>factionInvites</code>.
     */
    public static final Factioninvites FACTIONINVITES = Factioninvites.FACTIONINVITES;

    /**
     * The table <code>factionIslands</code>.
     */
    public static final Factionislands FACTIONISLANDS = Factionislands.FACTIONISLANDS;

    /**
     * The table <code>factionMembers</code>.
     */
    public static final Factionmembers FACTIONMEMBERS = Factionmembers.FACTIONMEMBERS;

    /**
     * The table <code>factions</code>.
     */
    public static final Factions FACTIONS = Factions.FACTIONS;

    /**
     * The table <code>islands</code>.
     */
    public static final Islands ISLANDS = Islands.ISLANDS;

    /**
     * The table <code>notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>playerData</code>.
     */
    public static final Playerdata PLAYERDATA = Playerdata.PLAYERDATA;

    /**
     * The table <code>trustedPlayers</code>.
     */
    public static final Trustedplayers TRUSTEDPLAYERS = Trustedplayers.TRUSTEDPLAYERS;
}
