/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database;


import net.skullian.skyfactions.database.tables.Auditlogs;
import net.skullian.skyfactions.database.tables.Defencelocations;
import net.skullian.skyfactions.database.tables.ElectionVotes;
import net.skullian.skyfactions.database.tables.FactionElections;
import net.skullian.skyfactions.database.tables.Factionbans;
import net.skullian.skyfactions.database.tables.Factioninvites;
import net.skullian.skyfactions.database.tables.Factionislands;
import net.skullian.skyfactions.database.tables.Factionmembers;
import net.skullian.skyfactions.database.tables.Factions;
import net.skullian.skyfactions.database.tables.FlywaySchemaHistory;
import net.skullian.skyfactions.database.tables.Islands;
import net.skullian.skyfactions.database.tables.Notifications;
import net.skullian.skyfactions.database.tables.Playerdata;
import net.skullian.skyfactions.database.tables.Trustedplayers;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>auditLogs</code>.
     */
    public static final Auditlogs AUDITLOGS = Auditlogs.AUDITLOGS;

    /**
     * The table <code>defenceLocations</code>.
     */
    public static final Defencelocations DEFENCELOCATIONS = Defencelocations.DEFENCELOCATIONS;

    /**
     * The table <code>election_votes</code>.
     */
    public static final ElectionVotes ELECTION_VOTES = ElectionVotes.ELECTION_VOTES;

    /**
     * The table <code>faction_elections</code>.
     */
    public static final FactionElections FACTION_ELECTIONS = FactionElections.FACTION_ELECTIONS;

    /**
     * The table <code>factionBans</code>.
     */
    public static final Factionbans FACTIONBANS = Factionbans.FACTIONBANS;

    /**
     * The table <code>factionInvites</code>.
     */
    public static final Factioninvites FACTIONINVITES = Factioninvites.FACTIONINVITES;

    /**
     * The table <code>factionIslands</code>.
     */
    public static final Factionislands FACTIONISLANDS = Factionislands.FACTIONISLANDS;

    /**
     * The table <code>factionMembers</code>.
     */
    public static final Factionmembers FACTIONMEMBERS = Factionmembers.FACTIONMEMBERS;

    /**
     * The table <code>factions</code>.
     */
    public static final Factions FACTIONS = Factions.FACTIONS;

    /**
     * The table <code>flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>islands</code>.
     */
    public static final Islands ISLANDS = Islands.ISLANDS;

    /**
     * The table <code>notifications</code>.
     */
    public static final Notifications NOTIFICATIONS = Notifications.NOTIFICATIONS;

    /**
     * The table <code>playerData</code>.
     */
    public static final Playerdata PLAYERDATA = Playerdata.PLAYERDATA;

    /**
     * The table <code>trustedPlayers</code>.
     */
    public static final Trustedplayers TRUSTEDPLAYERS = Trustedplayers.TRUSTEDPLAYERS;
}
