/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database;


import net.skullian.skyfactions.common.database.tables.ElectionVotes;
import net.skullian.skyfactions.common.database.tables.FactionElections;
import net.skullian.skyfactions.common.database.tables.FactionIslands;
import net.skullian.skyfactions.common.database.tables.FactionMembers;
import net.skullian.skyfactions.common.database.tables.Factions;
import net.skullian.skyfactions.common.database.tables.FlywaySchemaHistory;
import net.skullian.skyfactions.common.database.tables.Islands;
import net.skullian.skyfactions.common.database.tables.PlayerData;
import net.skullian.skyfactions.common.database.tables.TrustedPlayers;
import net.skullian.skyfactions.common.database.tables.records.ElectionVotesRecord;
import net.skullian.skyfactions.common.database.tables.records.FactionElectionsRecord;
import net.skullian.skyfactions.common.database.tables.records.FactionIslandsRecord;
import net.skullian.skyfactions.common.database.tables.records.FactionMembersRecord;
import net.skullian.skyfactions.common.database.tables.records.FactionsRecord;
import net.skullian.skyfactions.common.database.tables.records.FlywaySchemaHistoryRecord;
import net.skullian.skyfactions.common.database.tables.records.IslandsRecord;
import net.skullian.skyfactions.common.database.tables.records.PlayerDataRecord;
import net.skullian.skyfactions.common.database.tables.records.TrustedPlayersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ElectionVotesRecord> ELECTION_VOTES__PK_ELECTION_VOTES = Internal.createUniqueKey(ElectionVotes.ELECTION_VOTES, DSL.name("pk_election_votes"), new TableField[] { ElectionVotes.ELECTION_VOTES.ELECTION }, true);
    public static final UniqueKey<FactionElectionsRecord> FACTION_ELECTIONS__PK_FACTION_ELECTIONS = Internal.createUniqueKey(FactionElections.FACTION_ELECTIONS, DSL.name("pk_faction_elections"), new TableField[] { FactionElections.FACTION_ELECTIONS.ID }, true);
    public static final UniqueKey<FactionIslandsRecord> FACTION_ISLANDS__PK_FACTION_ISLANDS = Internal.createUniqueKey(FactionIslands.FACTION_ISLANDS, DSL.name("pk_faction_islands"), new TableField[] { FactionIslands.FACTION_ISLANDS.ID }, true);
    public static final UniqueKey<FactionMembersRecord> FACTION_MEMBERS__PK_FACTION_MEMBERS = Internal.createUniqueKey(FactionMembers.FACTION_MEMBERS, DSL.name("pk_faction_members"), new TableField[] { FactionMembers.FACTION_MEMBERS.UUID }, true);
    public static final UniqueKey<FactionsRecord> FACTIONS__PK_FACTIONS = Internal.createUniqueKey(Factions.FACTIONS, DSL.name("pk_factions"), new TableField[] { Factions.FACTIONS.NAME }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY__PK_FLYWAY_SCHEMA_HISTORY = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("pk_flyway_schema_history"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<IslandsRecord> ISLANDS__PK_ISLANDS = Internal.createUniqueKey(Islands.ISLANDS, DSL.name("pk_islands"), new TableField[] { Islands.ISLANDS.ID }, true);
    public static final UniqueKey<PlayerDataRecord> PLAYER_DATA__PK_PLAYER_DATA = Internal.createUniqueKey(PlayerData.PLAYER_DATA, DSL.name("pk_player_data"), new TableField[] { PlayerData.PLAYER_DATA.UUID }, true);
    public static final UniqueKey<TrustedPlayersRecord> TRUSTED_PLAYERS__PK_TRUSTED_PLAYERS = Internal.createUniqueKey(TrustedPlayers.TRUSTED_PLAYERS, DSL.name("pk_trusted_players"), new TableField[] { TrustedPlayers.TRUSTED_PLAYERS.ISLAND_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ElectionVotesRecord, FactionElectionsRecord> ELECTION_VOTES__FK_ELECTION_VOTES_PK_FACTION_ELECTIONS = Internal.createForeignKey(ElectionVotes.ELECTION_VOTES, DSL.name("fk_election_votes_pk_faction_elections"), new TableField[] { ElectionVotes.ELECTION_VOTES.ELECTION }, Keys.FACTION_ELECTIONS__PK_FACTION_ELECTIONS, new TableField[] { FactionElections.FACTION_ELECTIONS.ID }, true);
}
