/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database.tables.records;


import java.time.LocalDateTime;

import net.skullian.skyfactions.database.tables.Factionelections;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionelectionsRecord extends UpdatableRecordImpl<FactionelectionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>factionElections.id</code>.
     */
    public FactionelectionsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>factionElections.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>factionElections.factionName</code>.
     */
    public FactionelectionsRecord setFactionname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>factionElections.factionName</code>.
     */
    public String getFactionname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>factionElections.endDate</code>.
     */
    public FactionelectionsRecord setEnddate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>factionElections.endDate</code>.
     */
    public LocalDateTime getEnddate() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactionelectionsRecord
     */
    public FactionelectionsRecord() {
        super(Factionelections.FACTIONELECTIONS);
    }

    /**
     * Create a detached, initialised FactionelectionsRecord
     */
    public FactionelectionsRecord(Integer id, String factionname, LocalDateTime enddate) {
        super(Factionelections.FACTIONELECTIONS);

        setId(id);
        setFactionname(factionname);
        setEnddate(enddate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FactionelectionsRecord
     */
    public FactionelectionsRecord(net.skullian.skyfactions.database.tables.pojos.Factionelections value) {
        super(Factionelections.FACTIONELECTIONS);

        if (value != null) {
            setId(value.getId());
            setFactionname(value.getFactionname());
            setEnddate(value.getEnddate());
            resetChangedOnNotNull();
        }
    }
}
