/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ElectionVotes implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer election;
    private final String uuid;
    private final String votedFor;

    public ElectionVotes(ElectionVotes value) {
        this.election = value.election;
        this.uuid = value.uuid;
        this.votedFor = value.votedFor;
    }

    public ElectionVotes(
        Integer election,
        String uuid,
        String votedFor
    ) {
        this.election = election;
        this.uuid = uuid;
        this.votedFor = votedFor;
    }

    /**
     * Getter for <code>election_votes.election</code>.
     */
    public Integer getElection() {
        return this.election;
    }

    /**
     * Getter for <code>election_votes.uuid</code>.
     */
    public String getUuid() {
        return this.uuid;
    }

    /**
     * Getter for <code>election_votes.voted_for</code>.
     */
    public String getVotedFor() {
        return this.votedFor;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ElectionVotes other = (ElectionVotes) obj;
        if (this.election == null) {
            if (other.election != null)
                return false;
        }
        else if (!this.election.equals(other.election))
            return false;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.votedFor == null) {
            if (other.votedFor != null)
                return false;
        }
        else if (!this.votedFor.equals(other.votedFor))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.election == null) ? 0 : this.election.hashCode());
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.votedFor == null) ? 0 : this.votedFor.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ElectionVotes (");

        sb.append(election);
        sb.append(", ").append(uuid);
        sb.append(", ").append(votedFor);

        sb.append(")");
        return sb.toString();
    }
}
