/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Factionelections implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String factionname;
    private final LocalDateTime enddate;

    public Factionelections(Factionelections value) {
        this.id = value.id;
        this.factionname = value.factionname;
        this.enddate = value.enddate;
    }

    public Factionelections(
        Integer id,
        String factionname,
        LocalDateTime enddate
    ) {
        this.id = id;
        this.factionname = factionname;
        this.enddate = enddate;
    }

    /**
     * Getter for <code>factionElections.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>factionElections.factionName</code>.
     */
    public String getFactionname() {
        return this.factionname;
    }

    /**
     * Getter for <code>factionElections.endDate</code>.
     */
    public LocalDateTime getEnddate() {
        return this.enddate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Factionelections other = (Factionelections) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.factionname == null) {
            if (other.factionname != null)
                return false;
        }
        else if (!this.factionname.equals(other.factionname))
            return false;
        if (this.enddate == null) {
            if (other.enddate != null)
                return false;
        }
        else if (!this.enddate.equals(other.enddate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.factionname == null) ? 0 : this.factionname.hashCode());
        result = prime * result + ((this.enddate == null) ? 0 : this.enddate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Factionelections (");

        sb.append(id);
        sb.append(", ").append(factionname);
        sb.append(", ").append(enddate);

        sb.append(")");
        return sb.toString();
    }
}
