/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionElections implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer id;
    private final String factionName;
    private final LocalDateTime endDate;

    public FactionElections(FactionElections value) {
        this.id = value.id;
        this.factionName = value.factionName;
        this.endDate = value.endDate;
    }

    public FactionElections(
        Integer id,
        String factionName,
        LocalDateTime endDate
    ) {
        this.id = id;
        this.factionName = factionName;
        this.endDate = endDate;
    }

    /**
     * Getter for <code>faction_elections.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Getter for <code>faction_elections.faction_name</code>.
     */
    public String getFactionName() {
        return this.factionName;
    }

    /**
     * Getter for <code>faction_elections.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return this.endDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final FactionElections other = (FactionElections) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.factionName == null) {
            if (other.factionName != null)
                return false;
        }
        else if (!this.factionName.equals(other.factionName))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.factionName == null) ? 0 : this.factionName.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FactionElections (");

        sb.append(id);
        sb.append(", ").append(factionName);
        sb.append(", ").append(endDate);

        sb.append(")");
        return sb.toString();
    }
}
