/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import net.skullian.skyfactions.common.database.tables.pojos.AuditLogs;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuditLogsRecord extends TableRecordImpl<AuditLogsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>audit_logs.factionName</code>.
     */
    public AuditLogsRecord setFactionname(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>audit_logs.factionName</code>.
     */
    public String getFactionname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>audit_logs.type</code>.
     */
    public AuditLogsRecord setType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>audit_logs.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>audit_logs.uuid</code>.
     */
    public AuditLogsRecord setUuid(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>audit_logs.uuid</code>.
     */
    public String getUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>audit_logs.replacements</code>.
     */
    public AuditLogsRecord setReplacements(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>audit_logs.replacements</code>.
     */
    public String getReplacements() {
        return (String) get(3);
    }

    /**
     * Setter for <code>audit_logs.timestamp</code>.
     */
    public AuditLogsRecord setTimestamp(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>audit_logs.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditLogsRecord
     */
    public AuditLogsRecord() {
        super(net.skullian.skyfactions.common.database.tables.AuditLogs.AUDIT_LOGS);
    }

    /**
     * Create a detached, initialised AuditLogsRecord
     */
    public AuditLogsRecord(String factionname, String type, String uuid, String replacements, Long timestamp) {
        super(net.skullian.skyfactions.common.database.tables.AuditLogs.AUDIT_LOGS);

        setFactionname(factionname);
        setType(type);
        setUuid(uuid);
        setReplacements(replacements);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AuditLogsRecord
     */
    public AuditLogsRecord(AuditLogs value) {
        super(net.skullian.skyfactions.common.database.tables.AuditLogs.AUDIT_LOGS);

        if (value != null) {
            setFactionname(value.getFactionname());
            setType(value.getType());
            setUuid(value.getUuid());
            setReplacements(value.getReplacements());
            setTimestamp(value.getTimestamp());
            resetChangedOnNotNull();
        }
    }
}
