/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import net.skullian.skyfactions.common.database.tables.DefenceLocations;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DefenceLocationsRecord extends TableRecordImpl<DefenceLocationsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>defence_locations.uuid</code>.
     */
    public DefenceLocationsRecord setUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>defence_locations.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>defence_locations.type</code>.
     */
    public DefenceLocationsRecord setType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>defence_locations.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>defence_locations.factionName</code>.
     */
    public DefenceLocationsRecord setFactionname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>defence_locations.factionName</code>.
     */
    public String getFactionname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>defence_locations.x</code>.
     */
    public DefenceLocationsRecord setX(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>defence_locations.x</code>.
     */
    public Integer getX() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>defence_locations.y</code>.
     */
    public DefenceLocationsRecord setY(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>defence_locations.y</code>.
     */
    public Integer getY() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>defence_locations.z</code>.
     */
    public DefenceLocationsRecord setZ(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>defence_locations.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DefenceLocationsRecord
     */
    public DefenceLocationsRecord() {
        super(DefenceLocations.DEFENCE_LOCATIONS);
    }

    /**
     * Create a detached, initialised DefenceLocationsRecord
     */
    public DefenceLocationsRecord(String uuid, String type, String factionname, Integer x, Integer y, Integer z) {
        super(DefenceLocations.DEFENCE_LOCATIONS);

        setUuid(uuid);
        setType(type);
        setFactionname(factionname);
        setX(x);
        setY(y);
        setZ(z);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DefenceLocationsRecord
     */
    public DefenceLocationsRecord(net.skullian.skyfactions.common.database.tables.pojos.DefenceLocations value) {
        super(DefenceLocations.DEFENCE_LOCATIONS);

        if (value != null) {
            setUuid(value.getUuid());
            setType(value.getType());
            setFactionname(value.getFactionname());
            setX(value.getX());
            setY(value.getY());
            setZ(value.getZ());
            resetChangedOnNotNull();
        }
    }
}
