/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import net.skullian.skyfactions.common.database.tables.ElectionVotes;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ElectionVotesRecord extends UpdatableRecordImpl<ElectionVotesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>election_votes.election</code>.
     */
    public ElectionVotesRecord setElection(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>election_votes.election</code>.
     */
    public Integer getElection() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>election_votes.uuid</code>.
     */
    public ElectionVotesRecord setUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>election_votes.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>election_votes.votedFor</code>.
     */
    public ElectionVotesRecord setVotedfor(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>election_votes.votedFor</code>.
     */
    public String getVotedfor() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ElectionVotesRecord
     */
    public ElectionVotesRecord() {
        super(ElectionVotes.ELECTION_VOTES);
    }

    /**
     * Create a detached, initialised ElectionVotesRecord
     */
    public ElectionVotesRecord(Integer election, String uuid, String votedfor) {
        super(ElectionVotes.ELECTION_VOTES);

        setElection(election);
        setUuid(uuid);
        setVotedfor(votedfor);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ElectionVotesRecord
     */
    public ElectionVotesRecord(net.skullian.skyfactions.common.database.tables.pojos.ElectionVotes value) {
        super(ElectionVotes.ELECTION_VOTES);

        if (value != null) {
            setElection(value.getElection());
            setUuid(value.getUuid());
            setVotedfor(value.getVotedfor());
            resetChangedOnNotNull();
        }
    }
}
