/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import java.time.LocalDate;

import net.skullian.skyfactions.common.database.tables.pojos.FactionElections;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionElectionsRecord extends UpdatableRecordImpl<FactionElectionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>faction_elections.id</code>.
     */
    public FactionElectionsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>faction_elections.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>faction_elections.factionName</code>.
     */
    public FactionElectionsRecord setFactionname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>faction_elections.factionName</code>.
     */
    public String getFactionname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>faction_elections.endDate</code>.
     */
    public FactionElectionsRecord setEnddate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>faction_elections.endDate</code>.
     */
    public LocalDate getEnddate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactionElectionsRecord
     */
    public FactionElectionsRecord() {
        super(net.skullian.skyfactions.common.database.tables.FactionElections.FACTION_ELECTIONS);
    }

    /**
     * Create a detached, initialised FactionElectionsRecord
     */
    public FactionElectionsRecord(Integer id, String factionname, LocalDate enddate) {
        super(net.skullian.skyfactions.common.database.tables.FactionElections.FACTION_ELECTIONS);

        setId(id);
        setFactionname(factionname);
        setEnddate(enddate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FactionElectionsRecord
     */
    public FactionElectionsRecord(FactionElections value) {
        super(net.skullian.skyfactions.common.database.tables.FactionElections.FACTION_ELECTIONS);

        if (value != null) {
            setId(value.getId());
            setFactionname(value.getFactionname());
            setEnddate(value.getEnddate());
            resetChangedOnNotNull();
        }
    }
}
