/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import net.skullian.skyfactions.common.database.tables.pojos.FactionInvites;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionInvitesRecord extends TableRecordImpl<FactionInvitesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>faction_invites.factionName</code>.
     */
    public FactionInvitesRecord setFactionname(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>faction_invites.factionName</code>.
     */
    public String getFactionname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>faction_invites.uuid</code>.
     */
    public FactionInvitesRecord setUuid(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>faction_invites.uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>faction_invites.inviter</code>.
     */
    public FactionInvitesRecord setInviter(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>faction_invites.inviter</code>.
     */
    public String getInviter() {
        return (String) get(2);
    }

    /**
     * Setter for <code>faction_invites.type</code>.
     */
    public FactionInvitesRecord setType(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>faction_invites.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>faction_invites.timestamp</code>.
     */
    public FactionInvitesRecord setTimestamp(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>faction_invites.timestamp</code>.
     */
    public Long getTimestamp() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactionInvitesRecord
     */
    public FactionInvitesRecord() {
        super(net.skullian.skyfactions.common.database.tables.FactionInvites.FACTION_INVITES);
    }

    /**
     * Create a detached, initialised FactionInvitesRecord
     */
    public FactionInvitesRecord(String factionname, String uuid, String inviter, String type, Long timestamp) {
        super(net.skullian.skyfactions.common.database.tables.FactionInvites.FACTION_INVITES);

        setFactionname(factionname);
        setUuid(uuid);
        setInviter(inviter);
        setType(type);
        setTimestamp(timestamp);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FactionInvitesRecord
     */
    public FactionInvitesRecord(FactionInvites value) {
        super(net.skullian.skyfactions.common.database.tables.FactionInvites.FACTION_INVITES);

        if (value != null) {
            setFactionname(value.getFactionname());
            setUuid(value.getUuid());
            setInviter(value.getInviter());
            setType(value.getType());
            setTimestamp(value.getTimestamp());
            resetChangedOnNotNull();
        }
    }
}
