/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import net.skullian.skyfactions.common.database.tables.FactionMembers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionMembersRecord extends UpdatableRecordImpl<FactionMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>faction_members.factionName</code>.
     */
    public FactionMembersRecord setFactionname(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>faction_members.factionName</code>.
     */
    public String getFactionname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>faction_members.uuid</code>.
     */
    public FactionMembersRecord setUuid(byte[] value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>faction_members.uuid</code>.
     */
    public byte[] getUuid() {
        return (byte[]) get(1);
    }

    /**
     * Setter for <code>faction_members.rank</code>.
     */
    public FactionMembersRecord setRank(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>faction_members.rank</code>.
     */
    public String getRank() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<byte[]> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FactionMembersRecord
     */
    public FactionMembersRecord() {
        super(FactionMembers.FACTION_MEMBERS);
    }

    /**
     * Create a detached, initialised FactionMembersRecord
     */
    public FactionMembersRecord(String factionname, byte[] uuid, String rank) {
        super(FactionMembers.FACTION_MEMBERS);

        setFactionname(factionname);
        setUuid(uuid);
        setRank(rank);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised FactionMembersRecord
     */
    public FactionMembersRecord(net.skullian.skyfactions.common.database.tables.pojos.FactionMembers value) {
        super(FactionMembers.FACTION_MEMBERS);

        if (value != null) {
            setFactionname(value.getFactionname());
            setUuid(value.getUuid());
            setRank(value.getRank());
            resetChangedOnNotNull();
        }
    }
}
