/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.tables.records;


import net.skullian.skyfactions.common.database.tables.PlayerData;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PlayerDataRecord extends UpdatableRecordImpl<PlayerDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>player_data.uuid</code>.
     */
    public PlayerDataRecord setUuid(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>player_data.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>player_data.discord_id</code>.
     */
    public PlayerDataRecord setDiscordId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>player_data.discord_id</code>.
     */
    public String getDiscordId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>player_data.last_raid</code>.
     */
    public PlayerDataRecord setLastRaid(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>player_data.last_raid</code>.
     */
    public Long getLastRaid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>player_data.locale</code>.
     */
    public PlayerDataRecord setLocale(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>player_data.locale</code>.
     */
    public String getLocale() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerDataRecord
     */
    public PlayerDataRecord() {
        super(PlayerData.PLAYER_DATA);
    }

    /**
     * Create a detached, initialised PlayerDataRecord
     */
    public PlayerDataRecord(String uuid, String discordId, Long lastRaid, String locale) {
        super(PlayerData.PLAYER_DATA);

        setUuid(uuid);
        setDiscordId(discordId);
        setLastRaid(lastRaid);
        setLocale(locale);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised PlayerDataRecord
     */
    public PlayerDataRecord(net.skullian.skyfactions.common.database.tables.pojos.PlayerData value) {
        super(PlayerData.PLAYER_DATA);

        if (value != null) {
            setUuid(value.getUuid());
            setDiscordId(value.getDiscordId());
            setLastRaid(value.getLastRaid());
            setLocale(value.getLocale());
            resetChangedOnNotNull();
        }
    }
}
