#     _____      __  __  _
#   / ___/___  / /_/ /_(_)___  ____ ______
#   \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#  ___/ /  __/ /_/ /_/ / / / / /_/ (__  )
# /____/\___/\__/\__/_/_/ /_/\__, /____/
#                           /____/

# =============== SKYFACTIONS CONFIG =============== #

# DO NOT CHANGE THIS!!!!
config-version: 1

# Database config. Requires a restart to apply.
database:
  # You can either use 'sqlite' or 'sql' (MySQL). Default: sqlite.
  type: 'sqlite'

  # Connection values for MySQL if you decide to use it.
  # host: The MySQL Host. Format: "<host>[:<port>]". Port defaults to 3306.
  # name: The name of the database to use.
  # username: The MySQL User to use.
  # password: The Password for the MySQL User.
  # use-ssl: Whether to use SSL.
  database-host: ''
  database-name: ''
  database-username: ''
  database-password: ''
  use-ssl: true

  # Max lifetime for the database connection.
  # Format: MILLISECONDS
  max-lifetime: 30000

  # Max connection pool size.
  # Applies for both SQLite and MySQL
  max-pool-size: 10

  # Because SkyFactions is very heavy on the database, we use a cache service.
  # This will cache all island data modification, and will push it to the database at once.
  # The cache service will also run on server stop.
  # This means the database is not being repetitively interfaced with.
  # There are more cache systems used internally, such as caching playerdata on join.
  # You can modify the cache save interval here.
  # It is in seconds -> Default 10 minutes (600 seconds)
  cache-save-interval: 600

# This plugin has multi-language support.
# This means players in different locations are sent plugin messages in their native language.
language:
  # Language to use / fallback to if the plugin cannot find a player's language config.
  default-language: "en_US"

  # This is used in text-related things such as faction creation, broadcasts etc.
  # This supports both normal strings and regex.
  blacklisted-phrases:
    - cunt
    - retard
    - motherfucker
    - motherfuck
    - fuck
    - kys
    - penis
    - sped
    - bollocks
    - bastard
    - asshat
    - dumbass
    - slapper
    - anus
    - anal
    - cock
    - dick
    - whore
    - suck
    - twat
    - shit
    - bugger
    - arse
    - faggot
    - bitch
    - butt|ass(?:hole)?
    - ^fag$
    - nigg(?:a|er)
    - tit(?:s|z|ies)?
    - boob(?:s|z|ies)?

integration:
  itemjoin: true # On island deletion a player's inventory and enderchest are wiped. We can hook into ItemJoin and NOT wipe items from ItemJoin.
  coreprotect: true # On obelisk relocation and defence removal, we can hook into CoreProtect to log interactions.
  vault: true # Used in the NPC integration (for actions).
  placeholderapi: true # Hook into PlaceholderAPI and parse placeholders.
  jukebox: true # Hook into the Jukebox plugin, to stop playing music when a raid begins.
  noteblockapi: true # Hook into the NoteBlockAPI plugin, used to play music when a raid begins.
  mythicmobs: true # Hook into mythicmobs, used in defences. See https://docs.terrabytedev.com/skyfactions/mechanics/defences/integrations.html#mythicmobs for more info.

# SkyFactions Hub Config
hub:
  # Name of the world that the hub is located in.
  world-name: "world"

  # This is where players will spawn when they first join the server (you'd have to do that by setworldspawn or whatever).
  # Also where players are teleported when they do /hub or their island is deleted.
  hub-location: [ 0, 64, 0 ]

# Configuration for cooldowns.
# You do NOT want these to be too low, definitely not 0. These will avoid database spam and anything else.
cooldowns:
  command: 5000 # Cooldown for commands
  gui-item: 1500 # Global cooldown for all items

# Configuration for all sounds (apart from GUI item clicks, they are configured in their respective GUI config files)
# Set the sound to "NONE" to disable it.
sounds:
  # Sent when an island is successfully created.
  island-create-success: "ui.toast.challenge_complete"
  island-create-success-pitch: 1

  # Sound played when an ONLINE player is about to be raided. Repeats quickly for 5s.
  alarm-sound: "block.note_block.bell"
  alarm-pitch: 1

  # Sound when counting down for the start.
  countdown-sound: "block.note_block.hat"
  countdown-pitch: 1

  # Generally used in GUIs, when something goes wrong
  error-sound: "block.note_block.bass"
  error-sound-pitch: 1

  # Sent when a player purchases a defence successfully.
  defence-purchase-success-sound: "ui.toast.challenge_complete"
  defence-purchase-success-sound-pitch: 1

# GUI Related configurations
gui:
  # All GUIs allow you to specify the textures as "<player_skull>" which will display the player's skull texture.
  # This does look up profile properties for that player's UUID to mojang's auth servers which then looks up their skin.
  # If you are running offline-mode servers (does not apply to online-mode networks which have uuid forwarding to backends (resulting in a v4 UUID))
  # make sure you disable this, otherwise you will hit a lot of 429 errors.
  # The reason to disable this is that v3 uuids are not supported by mojang and you are just wasting bandwidth and spamming your logs.
  lookup-player-skins: true

  # A steve head (default)
  # Will replace all player_skull items with this if lookup-player-skins is false.
  override-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDEwNzA0NWU2NDk0NDg1NmY0YTQ3YzAxNjg4MWM2ZWFhNjI0NTNhODMyMmE5MmEwYzZjYzI0NDNlYjlhYmQzNCJ9fX0="

# General island config.
island:

  # Cooldown for island deletion (in milliseconds).
  # We don't put players on cooldown WHEN they delete, because then players have to wait to make a new island.
  # By putting a cooldown on deletion (upon creating an island), players have an actual island to play on for whatever reason, rather
  # than being stuck in the actual lobby. Fun right?
  # This also prevents players from spamming and causing lag.
  deletion-cooldown: 7200000 # 2 Hours

  # Name of the world where faction islands will be located.
  faction-world-name: "faction_islands"
  # Name of the world where player islands will be located.
  island-world-name: "player_islands"

  # Name of the WorldEdit schematic file for the normal island. MUST INCLUDE THE FILE EXTENSION!
  normal-island-schematic: 'island.schem'
  # Name of the WorldEdit schematic file for the faction island. MUST INCLUDE THE FILE EXTENSION!
  faction-island-schematic: 'faction_island.schem'

  # Whether to teleport the player to their island when they join.
  teleport-on-join: false

  # Whether to teleport the player to their island on death / respawn.
  teleport-on-death: true

  # Prevent players from entering nether portals in the overworld and nether. (and any other dimensions).
  # This is so players can't get into other islands, and cause havoc.
  prevent-nether-portals: true
  # Assuming prevent-nether-portals is set to true, you can specify dimensions where players CAN enter nether portals.
  allowed-dimensions:
    - "my_world_name"

# SkyFactions can hook into numerous NPC plugins to add support
# for per-island NPCs, such as Jerry from Hypixel SkyBlock.
# You can configure the system for this here.
npc:
  # Whether the NPC system should be enabled or not.
  # If you disable this after previously having it enabled, YOU MUST RUN /sf disablenpcs
  enabled: false

  # If you have updated the skin of the NPC, or any other attribute you must
  # run /sf updatenpcs.

  # Specify which NPC plugin (factory) to use.
  # Possible factories: "znpcpsplus" / "fancynpcs"
  # Specifing an invalid factory or a factory that is not installed will
  # cause the plugin to disable.
  factory: "znpcsplus"

  # Customise the entity of the NPC.
  # See https://jd.papermc.io/paper/1.21.1/org/bukkit/entity/EntityType.html for a list
  # of valid entity types.
  entity:
    # Entity type for player islands.
    player-islands: "PLAYER"

    # Entity type for faction islands.
    faction-islands: "PLAYER"

  # Configure the names of the NPC.
  # Unfortunately these cannot be configure in individual language files due to limitations. (Global Only).
  names:
    # NPC name for player islands,
    # You can use the placeholder "%player_name%" to display the name of the player.
    # This placeholder does not apply for faction island NPC names!
    player-islands: "&9Sky Master"

    # NPC Name for faction islands.
    # You can use the placeholder "%faction_name%" to display the name of the faction instead.
    faction-islands: "&9Sky Master"

  # Allows you to configure the skin of the NPCs for island and faction islands
  # Skin Format:
  # "url:skin_url_here" - Specify a URL to a skin texture: ZNPCsPlus and FancyNPCs only.
  # "player:name_of_player_here" - Specify the name of a player who's skim you want to display.
  # "texture:texture_data_here" - Provide the texture data of the skin manually.
  # None - no player skin, will go to the default of whatever factory provider plugin you use.
  skins:
    # Skin of the NPC on player islands.
    # You can use the placeholder "%player_name%" for it to be the skin of the island's owner.
    # The above placeholder does not work on the Faction Island NPC skins!
    player-islands: "player:%player_name%"

    # Skin of the NPC on faction islands.
    # You can use the "%faction_owner%" placeholder to display the skim of the faction's owner.
    faction-islands: "player:%faction_owner"

  # This allows you to configure the offsets of where the NPC
  # will spawn, relative to the center of the island.
  offsets:
    # How far from the center of player islands should the NPC be spawned?
    player-islands: [ 2, 0, 2 ] # [x, y, z]

    # How far from the center of faction islands should the NPC be spawned?
    faction-islands: [ 2, 0, 2 ] # [x, y, z]

# Island grid generation algorithm configuration
generation:
  player-islands:
    # Radius of each player region. The islands will be generated here, in the center of each region.
    region-size: 200
    # Space between region islands.
    region-padding: 100
    # The center point where all islands start. [X, Y, Z]
    grid-origin: [ 0, 64, 0 ]

  faction-islands:
    # Radius of each faction region. The islands will be generated here, in the center of each region.
    region-size: 300
    # Space between region islands.
    region-padding: 100
    # The center point where all islands start. [X, Y, Z]
    grid-origin: [ 0, 64, 0 ]

gems:
  # Whether gems can be withdrawed into item form, and back.
  # Disabling this will remove the /gems withdraw and /gems deposit commands.
  can-withdraw: true

  # The withdrawable item format of the gems.
  # You can find a list of items at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html.
  material: "EMERALD"

  # Item lore for the gem.
  item-lore: [ ] # No lore for me!

  # Custom Model Data / ID for the block (if you want it). Keep at -1 to disable the feature.
  custom-model-data: -1

raiding:
  # Cost of raiding a user in Gems.
  raiding-cost: 2

  # Cooldown for raiding (in milliseconds).
  raiding-cooldown: 10800000 # 3 Hours
  # Cooldown for being raided (in milliseconds).
  raided-cooldown: 86400000 # 24 Hours

  # After a player has created their island, they will be immune to being raided for this specified amount of time (in milliseconds).
  player-raid-immunity: 21600000 # 6 Hours
  # After a Faction has created their island, they will be immune to being raided for this specified amount of time (in milliseconds).
  faction-raid-immunity: 21600000 # 6 Hours

  # Height of where the attackers of a raid will spawn
  spawn-height: 250

  # List of .nbs song names that are played when raiding (IN ORDER).
  # Requires NoteBlockAPI to be installed and enabled in the integrations section.
  music-file-names:
    - The_Grounds_Color_Is_Yellow.nbs

  # Players are spawned in a random pos at SPAWN_HEIGHT. The radius from the centre of the region is dictated here.
  random-spawn-radius: 30

  # After preparation, how long should the countdown last?
  countdown-duration: 5 # IN SECONDS

  # This is a feature where players can be teleported to areas to prepare themselves for the raid.
  teleport-to-preparation: true
  # This is the name of the world where raid defenders will be teleported to be prepared for the raid.
  # Can be the same as the Hub world or normal world if you wish.
  raid-preparation-world: "world"
  # Position where raid defenders are spawned to be prepared for the raid.
  # [x, y, z]
  raid-preparation-pos: [ 0, 64, 0 ]
  # Time in seconds that they are in the preparation area before being teleported back to their island.
  raid-preparation-time: 30

factions:
  # All configurations related to creation factions.
  faction-creation:

    # Cooldown for faction creation (in milliseconds).
    # We don't put players on cooldown WHEN they create, because then players have to wait to make a new faction.
    # By putting a cooldown on deletion (upon creating an island), players have an actual faction island to play on for whatever reason, rather
    # than being stuck in the actual lobby. Fun right?
    # This also prevents players from spamming and causing lag.
    deletion-cooldown: 10800000 # 3 Hours

    # Cost of creating a faction in player runes.
    # Set this to 0 if you wish it to be free.
    creation-cost: 100

    # Minimum length of faction name.
    minimum-name-length: 3
    # Maximum length of faction name.
    maximum-name-length: 16

    # Whether to allow numbers in the name.
    allow-numbers: true
    # Whether to allow non-english characters & numbers in the name.
    allow-non-english: false
    # Allow symbols in the name.
    allow-symbols: false

  # Configuration for faction renaming.
  # The control measures (min/max name length, blacklisted keywords, allow symbols/numbers/non-english) in the faction-creation section (above)
  # will apply here, so don't worry!
  faction-renaming:
    # Allow renaming outright. This will mean players cannot even access /faction rename.
    allow-renaming: true

    # Cost in runes to rename the faction.
    # Set this to 0 for it to be free.
    rename-cost: 200

    # Time (in milliseconds) between being able to rename your faction.
    cooldown: 86400000 # 7 Days

  # Configure who can do certain actions.
  # Possible Ranks: "owner", "admin", "moderator", "fighter", "member"
  # Some permission configs are in the defences.yml configuration.
  faction-ranks:

    # Who can ban other members?
    ban: ["owner", "admin"]

    # Who can ban other members?
    kick: ["owner", "admin", "moderator"]

    # Who can promote and demote members?
    manage-rank: ["owner", "admin"]

    # Who can change the Faction MOTD? (Persistent)
    modify-motd: ["owner", "admin"]

    # Who can manage faction invites? (Create, accept, deny)
    manage-invites: ["owner", "admin"]

    # Who can create new broadcasts?
    create-broadcast: ["owner", "admin", "moderator"]

  faction-manage:

    # Whether to broadcast kicks, and the reason for it.
    broadcast-kicks: true

    # Whether to broadcast bans, and the reason for it.
    broadcast-bans: true

    manage-rank:
      # As a special aesthetic effect, show the selected item as enchanted.
      show-enchanted: true

# Notifications notify the player of things like pending invites (faction join requests, or player faction invites).
notifications:

  # Interval in which the notifications are sent.
  # IN SECONDS!
  interval: 60 # TODO MOVE TO 10m AFTER DEVELOPMENT