/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.database.tables;


import java.util.Collection;

import net.skullian.skyfactions.database.DefaultSchema;
import net.skullian.skyfactions.database.Keys;
import net.skullian.skyfactions.database.tables.records.FactionMembersRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class FactionMembers extends TableImpl<FactionMembersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>faction_members</code>
     */
    public static final FactionMembers FACTION_MEMBERS = new FactionMembers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FactionMembersRecord> getRecordType() {
        return FactionMembersRecord.class;
    }

    /**
     * The column <code>faction_members.factionName</code>.
     */
    public final TableField<FactionMembersRecord, String> FACTIONNAME = createField(DSL.name("factionName"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>faction_members.uuid</code>.
     */
    public final TableField<FactionMembersRecord, String> UUID = createField(DSL.name("uuid"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>faction_members.rank</code>.
     */
    public final TableField<FactionMembersRecord, String> RANK = createField(DSL.name("rank"), SQLDataType.VARCHAR, this, "");

    private FactionMembers(Name alias, Table<FactionMembersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private FactionMembers(Name alias, Table<FactionMembersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>faction_members</code> table reference
     */
    public FactionMembers(String alias) {
        this(DSL.name(alias), FACTION_MEMBERS);
    }

    /**
     * Create an aliased <code>faction_members</code> table reference
     */
    public FactionMembers(Name alias) {
        this(alias, FACTION_MEMBERS);
    }

    /**
     * Create a <code>faction_members</code> table reference
     */
    public FactionMembers() {
        this(DSL.name("faction_members"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<FactionMembersRecord> getPrimaryKey() {
        return Keys.FACTION_MEMBERS__PK_FACTION_MEMBERS;
    }

    @Override
    public FactionMembers as(String alias) {
        return new FactionMembers(DSL.name(alias), this);
    }

    @Override
    public FactionMembers as(Name alias) {
        return new FactionMembers(alias, this);
    }

    @Override
    public FactionMembers as(Table<?> alias) {
        return new FactionMembers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FactionMembers rename(String name) {
        return new FactionMembers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FactionMembers rename(Name name) {
        return new FactionMembers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FactionMembers rename(Table<?> name) {
        return new FactionMembers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactionMembers where(Condition condition) {
        return new FactionMembers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactionMembers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactionMembers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactionMembers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactionMembers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactionMembers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactionMembers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public FactionMembers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactionMembers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public FactionMembers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
