@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package net.skullian.skyfactions.common.database.jooq.keys


import net.skullian.skyfactions.common.database.jooq.tables.FlywaySchemaHistory
import net.skullian.skyfactions.common.database.jooq.tables.Islands
import net.skullian.skyfactions.common.database.jooq.tables.records.FlywaySchemaHistoryRecord
import net.skullian.skyfactions.common.database.jooq.tables.records.IslandsRecord

import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val FLYWAY_SCHEMA_HISTORY__PK_FLYWAY_SCHEMA_HISTORY: UniqueKey<FlywaySchemaHistoryRecord> = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("pk_flyway_schema_history"), arrayOf(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK), true)
val ISLANDS__PK_ISLANDS: UniqueKey<IslandsRecord> = Internal.createUniqueKey(Islands.ISLANDS, DSL.name("pk_islands"), arrayOf(Islands.ISLANDS.ID), true)
