name: Publish API

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Build & Publish
        env:
          repo_username: ${{ secrets.REPO_USERNAME }}
          repo_password: ${{ secrets.REPO_PASSWORD }}
        run: ./gradlew :api:publish