name: Publish API

on:
  release:
    types: [ "published" ]
  push:
    branches: [ "main", "refactor/v2" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        name: Set up JDK 21
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build & Publish
        env:
          repo_username: ${{ secrets.REPO_USERNAME }}
          repo_password: ${{ secrets.REPO_PASSWORD }}
        run: ./gradlew :api:publish