name: SkyFactionsReborn
version: '${version}'

main: net.skullian.skyfactions.paper.SkyFactionsReborn
loader: net.skullian.skyfactions.paper.SkyLoader

description: An advanced plugin core merging Skyblock and Factions together.
api-version: '1.21'

authors: [ Skullians, nouish, JerichoTorrent ]
website: "https://github.com/TerraByteDev/SkyFactionsReborn"
contributors:
  - ProGamingDK
  - DannyX
  - Kioku
  - Haibun
  - Kishku
  - ZephyrZymbol
  - imMohika